[metadata]
author = "Chua Bok Woon"

["templates/plainsimple/post-index.html"]
include = [
    "templates/plainsimple/header.html",
    "templates/plainsimple/footer.html",
    "templates/plainsimple/style.css",
    "templates/plainsimple/post-index.js",
]
    ["templates/plainsimple/post-index.html".content_security_policy]
    script-src = [ "stackpath.bootstrapcdn.com", "code.jquery.com" ]
    style-src = [ "stackpath.bootstrapcdn.com", "fonts.googleapis.com" ]
    img-src = [ "source.unsplash.com", "images.unsplash.com" ]
    font-src = [ "fonts.gstatic.com" ]

["templates/plainsimple/post.html"]
include = [
    "templates/plainsimple/header.html",
    "templates/plainsimple/style.css",
    "templates/plainsimple/post.js",
]

["templates/plainsimple/index.html"]
include = [
    "templates/plainsimple/style.css",
]
